# Generated by Django 5.0.2 on 2024-02-22 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prompt', '0002_prompt_delete_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('response', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prompt.prompt')),
            ],
        ),
    ]
