# Generated by Django 5.0.2 on 2024-02-22 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0002_rename_prompt_response_prompt_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='prompt_id',
            new_name='unique_link',
        ),
    ]
