# Generated by Django 5.0.2 on 2024-02-22 15:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompt', '0002_prompt_delete_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='unique_link',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
