# Generated by Django 5.0.2 on 2024-03-08 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prompt', '0003_prompt_unique_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prompt',
            name='unique_link',
        ),
    ]
