# Generated by Django 5.0.2 on 2024-03-08 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0002_response_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='user_id',
            new_name='prompt_id',
        ),
    ]
